### ISSUE TITLE
windows agent service installer

### ISSUE THREAD

**Issue by kregory** [sos-berlin/js7#13]
After installing service using install_agent_windows_service.cmd, the service don't launch.
The issue is in the params passed to the java. 
Line 127 may be changed to 

set SERVICE_STARTPARAMS=/C;\"bin\agent.cmd start --http-port=%JS7_AGENT_HTTP_PORT% %HTTPS_PORT_OPTION% --data-directory=\\\"%JS7_AGENT_DATA%\\\"\"

**Comment by sosap** [comment]
Thank you, we confirm that the quoting in the existing script does not match all situations, for example you are not using an Agent Instance Start Script agent_<port>.cmd, but the Agent Start Script agent.cmd.

With release 2.7.2 we will switch to a simplified version:

set SERVICE_STARTPARAMS=/C;bin\agent.cmd start --http-port=%JS7_AGENT_HTTP_PORT% %HTTPS_PORT_OPTION% --data-directory=""%JS7_AGENT_DATA%""
