### ISSUE TITLE
Issue during installation on Windows Server 2012 R2 (French language)

### ISSUE THREAD

**Issue by elie-mpo** [sos-berlin/js7#2]
Hi,

It seems that there's an encoding issue during the installation process (tested with v.2.2.3 and 2.3.0 on Windows Server 2012 R2 (French), issue occurs on Cockpit, Controller and Agent installation). The first step that is retrieving user account is generating this log : `java.io.IOException: Invalid account 'Syst$me'`.

However, this does not seem to affect the behavior of the software

**Comment by elie-mpo** [comment]
Yes, 'Système' is the correct spelling.

Here are the 3 logs files :
[Agent_Install_V2.3.0_20220428132402_8319110040562550083.log](https://github.com/sos-berlin/js7/files/8583495/Agent_Install_V2.3.0_20220428132402_8319110040562550083.log)
[Controller_Install_V2.3.0_20220428132152_5081730172026995534.log](https://github.com/sos-berlin/js7/files/8583496/Controller_Install_V2.3.0_20220428132152_5081730172026995534.log)
[JOC_Install_V2.3.0_20220428131757_2219487620477550970.log](https://github.com/sos-berlin/js7/files/8583497/JOC_Install_V2.3.0_20220428131757_2219487620477550970.log)

Also on 2.2.3 we could run orders without any issue, but on 2.3.0 it remains in blocked state (We are currently investigating)

**Comment by sosap** [comment]
We are currently investigating the issue about blocked orders after upgrade to 2.3.0. 

Can you please forward the controller.log and agent.log files?

A workaround is to delete the Agent from JOC Cockpit, optionally after revoking workflows from the Controller (that later on can be redeployed). The contents of the Controller's and Agent's "state" directory should be removed and both components restarted. When the Agent is then added to JOC Cockpit it should switch to the "coupled" status and should accept orders.

**Comment by sosap** [comment]
This behavior is a confirmed bug that is tracked with [JS-1990: Agent is coupled but orders are blocked after upgrade to release 2.3.0](https://change.sos-berlin.com/browse/JS-1990)

Please apply the workaround indicated with the issue description.

**Comment by sosap** [comment]
The Installer problem is tracked with [SET-207: JS7 Installers consider Windows code page](https://change.sos-berlin.com/browse/SET-207)

**Comment by elie-mpo** [comment]
Hi,

"java.io.IOException: Invalid account 'SystŠme'" is still present during installation/upgrade process. Otherwise everything has been fixed on blocked order.

Thanks
