### ISSUE TITLE
Docker pull sosberlin/js7:joc-2-3-3 error on manifest

### ISSUE THREAD

**Issue by PauloLaScience** [sos-berlin/js7#3]
Hi,
When I try `docker image pull sosberlin/js7:joc-2-3-3` I get an error:
`Error response from daemon: manifest for sosberlin/js7:joc-2-3-3 not found: manifest unknown: manifest unknown`

I'm following your Installation guide from [JS7 doc](http://js7.sh)
And running on wsl
```
paul@6Z7T2D3:~$ docker --version
Docker version 20.10.14, build a224086
paul@6Z7T2D3:~$

```
Kind regards
PauloLaScience

**Comment by sosap** [comment]
Hi Pauolo,

the is no docker image joc-2-3-3. This is what the error message tells you. If you found the wrong release number in the docs then please let us know the relevant page.

We recently published the image joc-2-3-1, therefore please use: docker pull sosberlin/js7:joc-2-3-1

Best regards
Andreas

**Comment by PauloLaScience** [comment]
Hi,
It's working fine with your suggestion.
Find it [here](https://kb.sos-berlin.com/display/PKB/JS7+-+JOC+Cockpit+Installation+for+Docker+Containers)
Best regards,
PauloLaScience
