### ISSUE TITLE
"Edit XML" not working as expected in Confguration Editor

### ISSUE THREAD

**Issue by rfx77** [sos-berlin/js7#6]
When using "Edit XML" in the Configuration Editor for example on notifications, the changes are not stored after pressing "Submit".

But when you press "Submit" then change to another Section in the UI and go back to notifications then the "Release" button is orange and you can see the cahnges from "Edit XML" and deploy them.

So to reproduce: 
*) Go to Configuration->Notifications
You can see the timezone in the first MessageFragments
*) Click "Edit XML" and change the timezone
*) Click "Submit"
Now the edit window closes and you can see that the timezone has NOT changed.
*) Go to Configuration->Inventory
*) Go to Configuration->Notifications
Now you see that the timezone has changed and you can click "Release"

I am on version 2.6.0

**Comment by sosap** [comment]
Thank you, we will address the issue. 

Changes are stored automatically to a draft version, the "Release" button makes changes to notification settings available to the Monitoring Service. However, the GUI does not consider direct changes to XML a trigger to offer such changes to be released. This is wrong, this will be fixed.

**Comment by sosap** [comment]
This issue is fixed with release [2.5.4](https://kb.sos-berlin.com/x/THOwBQ) and [2.6.1](https://kb.sos-berlin.com/x/hAy3Bg) respectively.
